monolog:
    use_microseconds: true,
    channels: [ 'main', 'app', 'rabbit' ],
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/main.log"
            level: debug
            channels: ["!event", "!rabbit"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        rabbit:
            type: rotating_file
            max_files: 3
            path: "%kernel.logs_dir%/%kernel.environment%/rabbit.json"
            level: debug
            channels: ["rabbit"]
            formatter: 'monolog.formatter.json'
