sentry:
    register_error_listener: false

monolog:
    use_microseconds: true,
    channels: [ 'main', 'app', 'rabbit', 'sentry'],
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [401, 422, 404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/app.json"
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!rabbit"]
        rabbit:
            type: rotating_file
            max_files: 21
            channels: ["rabbit"]
            path: "%kernel.logs_dir%/%kernel.environment%/rabbit.json"
            level: debug
            formatter: 'monolog.formatter.lz_processor'
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface

